### ISSUE TITLE
ASP application

### ISSUE THREAD

**Issue by CaydenPierce** [emexlabs/WearableIntelligenceSystem#10]
The current ASP application is basically a souped up MediaPipe example running our custom MediaPipe Perception Pipeline.  

We need to make it reliably run on the ASP for many hours/days at a time, in the background, always available to receive a connection and/or requests from the ASG.

## TODO
- [x] get app editing/building in Android studio - not essential but will help development speed
- [x] get current MediaPipe inferencing and ASG socket stuff running in an Android Service - determine the best type of service (Background, Foreground, Bound, etc.) to do the job. Likely needs a Foreground service like [here](https://robertohuertas.com/2019/06/29/android_foreground_services/)
- [x] start saving incoming images/video stream from ASG into a file structure that makes sense
- [x] setup database on Android with SqlLite or Realm
- [x] save image data (file location, timestamp, metadata) in database
- [x] setup a WebSocket connection on ASP that will run always in background - this will accept sensor data, function requests, and push data to the ASG
- [x] stream audio data from ASG to ASP - either over raw TCP socket or over the new WebSocket above

**Comment by CaydenPierce** [comment]
All done. We have moved all of the main components to ASP. Still need to implement a web system so we don't lose previous features that GLBOX handled - need to make GLBOX an HTTP server we occasionally hit for those things. Continuing this in other issues.
