### ISSUE TITLE
Voice Command on ASP

### ISSUE THREAD

**Issue by CaydenPierce** [emexlabs/WearableIntelligenceSystem#12]
Note: this relies on completion of #11  

This is part of the move to no longer streaming sensor data over the internet.

## Voice Command on ASP

The entire voice command is written in Python on the GLBOX. However, text parsing is not very complicated, so porting to Android should be straightforward, and doing so will avoid the latency and wastefulness of transcribing locally then streaming results to the web for processing.

## TODO
- [x] parse wake words
- [x] parse commands
- [x] parse arguments
- [x] implement wolfram search function
- [x] implement azure photo search function
- [x] implement wikipedia search function
- [x] run functions based on command
- [x] allow some wake words to also be commands

**Comment by CaydenPierce** [comment]
All done
